import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutHeader } from "./layout/layoutPart";
import { LayoutAside } from "./layout/layoutAside";
import { Var } from "./context/usecontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en"  >
      <Var>
        <body className={inter.className}>
          <div className="max">
            <LayoutHeader />
            <div className="share">
              <LayoutAside />
              {children}
            </div>
          </div>
        </body>
      </Var>
    </html>
  );
}
